version: '3.7'

services:
  pocsqldata:
    image: postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_HOSTNAME: kafka1

  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "29093:29092"
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_ADVERTISED_HOSTNAME: kafka2

  kafka3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka3
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "29094:29092"
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_ADVERTISED_HOSTNAME: kafka3

  kafdrop:
    container_name: kafdrop
    hostname: kafdrop
    image: kavimaluskam/kafdrop
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      LISTEN: "9000"
      SCHEMA_REGISTRY_URL: "http://schema_registry:8081"

  schema_registry:
    container_name: schema_registry
    hostname: schema_registry
    image: confluentinc/cp-schema-registry:5.1.0
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"

  schema_registry_ui:
    container_name: schema_registry_ui
    hostname: schema_registry_ui
    image: landoop/schema-registry-ui
    ports:
      - "8082:8000"
    environment:
      SCHEMAREGISTRY_URL: "http://localhost:8081"

  product-api:
    image: product-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile
    depends_on:
      - pocsqldata
      - kafka1
      - kafka2
      - kafka3

  recipe-api-1:
    image: recipe-api-1:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Recipe/Recipe.API/Dockerfile
    depends_on:
      - pocsqldata
      - kafka1
      - kafka2
      - kafka3

  recipe-api-2:
    image: recipe-api-2:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Recipe/Recipe.API/Dockerfile
    depends_on:
      - pocsqldata
      - kafka1
      - kafka2
      - kafka3

  recipe-api-3:
    image: recipe-api-3:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Recipe/Recipe.API/Dockerfile
    depends_on:
      - pocsqldata
      - kafka1
      - kafka2
      - kafka3

