version: '3.7'

services:
  pocsqldata:
    image: postgres

  product-api:
    image: product-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile
    depends_on:
      - pocsqldata

  recipe-api:
    image: recipe-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Recipe/Recipe.API/Dockerfile
    depends_on:
      - pocsqldata

